export const jsonFieldsNames = [
['tdate','Trade Date'],
['vdate','Value Date'],
['secid_name','SedID'],
['cpty','CounterParty'],
['qty','Qantity'],
['allocatedqty','Allocated'],
['price','Price'],
['trtype','Type'],
['tidinstrument','tidinstrument'],
['trade_amount','Trade Amount'],
['details','Details'],
['accured_interest','Accured Interest'],
['settlement_amount','Settlement Amount'],
['settlement_rate','Rate'],
['idtrade','ID' ],
['mp_name','ModelPortfolio'],
['secid','SecID'],
['id','ID'],
['generated','Generated'],
['allocated','Allocated'],
['unexecuted','Unexecuted'],
['amount','Amount'],
['status','Status'],
['idcurrency','Currency ID'],
['currencycode','Currency Code'],
['type','Type'],
]