insert into moexboards
select * from json_populate_recordset(null::moexboards, 
        '[
{"id": 177, "board_group_id": 57, "engine_id": 1, "market_id": 1, "boardid": "TQIF", "board_title": "Т+: Паи - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 178, "board_group_id": 57, "engine_id": 1, "market_id": 1, "boardid": "TQTF", "board_title": "Т+: ETF - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 129, "board_group_id": 57, "engine_id": 1, "market_id": 1, "boardid": "TQBR", "board_title": "Т+: Акции и ДР - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 130, "board_group_id": 57, "engine_id": 1, "market_id": 1, "boardid": "TQBS", "board_title": "Т+: А2-Акции и паи - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 131, "board_group_id": 57, "engine_id": 1, "market_id": 1, "boardid": "TQNL", "board_title": "Т+: Б-Акции и паи - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 132, "board_group_id": 57, "engine_id": 1, "market_id": 1, "boardid": "TQLV", "board_title": "Т+: В-Акции и ДР - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 133, "board_group_id": 57, "engine_id": 1, "market_id": 1, "boardid": "TQLI", "board_title": "Т+: И-Акции - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 134, "board_group_id": 57, "engine_id": 1, "market_id": 1, "boardid": "TQNE", "board_title": "Т+: Акции, паи и ДР внесписочные - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 158, "board_group_id": 57, "engine_id": 1, "market_id": 1, "boardid": "TQDE", "board_title": "Т+: Акции Д - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 401, "board_group_id": 57, "engine_id": 1, "market_id": 1, "boardid": "TQPI", "board_title": "Т+: Акции ПИР - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 225, "board_group_id": 156, "engine_id": 1, "market_id": 1, "boardid": "TQTD", "board_title": "Т+: ETF (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 429, "board_group_id": 156, "engine_id": 1, "market_id": 1, "boardid": "TQFD", "board_title": "Т+: ПАИ (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 431, "board_group_id": 156, "engine_id": 1, "market_id": 1, "boardid": "TQPD", "board_title": "Т+: Акции ПИР (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1, "board_group_id": 6, "engine_id": 1, "market_id": 1, "boardid": "EQBR", "board_title": "Основной режим: А1-Акции и паи - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 2, "board_group_id": 6, "engine_id": 1, "market_id": 1, "boardid": "EQBS", "board_title": "Основной режим: А2-Акции и паи - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 4, "board_group_id": 6, "engine_id": 1, "market_id": 1, "boardid": "EQNL", "board_title": "Основной режим: Б-Акции и паи - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 3, "board_group_id": 6, "engine_id": 1, "market_id": 1, "boardid": "EQLV", "board_title": "Основной режим: В-Акции и РДР - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 117, "board_group_id": 6, "engine_id": 1, "market_id": 1, "boardid": "EQDE", "board_title": "Основной режим: Акции Д - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 28, "board_group_id": 6, "engine_id": 1, "market_id": 1, "boardid": "EQLI", "board_title": "Основной режим: И-Акции - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 5, "board_group_id": 6, "engine_id": 1, "market_id": 1, "boardid": "EQNE", "board_title": "Основной режим: Акции и паи внесписочные - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 281, "board_group_id": 125, "engine_id": 1, "market_id": 1, "boardid": "SPEQ", "board_title": "Поставка по СК (акции)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 36, "board_group_id": 21, "engine_id": 1, "market_id": 1, "boardid": "SMAL", "board_title": "Т+: Неполные лоты (акции) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 305, "board_group_id": 42, "engine_id": 1, "market_id": 1, "boardid": "TQDP", "board_title": "Крупные пакеты - Акции - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 100, "board_group_id": 42, "engine_id": 1, "market_id": 1, "boardid": "EQDP", "board_title": "Крупные пакеты - Акции - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 260, "board_group_id": 99, "engine_id": 1, "market_id": 1, "boardid": "EQTD", "board_title": "Т0: ETF (USD) - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 313, "board_group_id": 157, "engine_id": 1, "market_id": 1, "boardid": "TQBE", "board_title": "Т+: Акции и ДР (EUR) - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 314, "board_group_id": 157, "engine_id": 1, "market_id": 1, "boardid": "TQTE", "board_title": "Т+: ETF (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 441, "board_group_id": 157, "engine_id": 1, "market_id": 1, "boardid": "TQFE", "board_title": "Т+: ПАИ (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 443, "board_group_id": 157, "engine_id": 1, "market_id": 1, "boardid": "TQPE", "board_title": "Т+: Акции ПИР (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1216, "board_group_id": 1215, "engine_id": 1, "market_id": 1, "boardid": "TQTY", "board_title": "Т+: ПАИ (CNY) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1217, "board_group_id": 1215, "engine_id": 1, "market_id": 1, "boardid": "TQPY", "board_title": "Т+: Акции ПИР (CNY) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 315, "board_group_id": 159, "engine_id": 1, "market_id": 1, "boardid": "EQTU", "board_title": "Т0: ETF (EUR) - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 1239, "board_group_id": 1238, "engine_id": 1, "market_id": 1, "boardid": "TQTH", "board_title": "Т+: ПАИ (HKD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1240, "board_group_id": 1238, "engine_id": 1, "market_id": 1, "boardid": "TQPH", "board_title": "Т+: Акции ПИР (HKD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 95, "board_group_id": 30, "engine_id": 1, "market_id": 1, "boardid": "EQCC", "board_title": "ЦК - режим основных торгов - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 135, "board_group_id": 58, "engine_id": 1, "market_id": 2, "boardid": "TQOB", "board_title": "Т+: Гособлигации - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 136, "board_group_id": 58, "engine_id": 1, "market_id": 2, "boardid": "TQOS", "board_title": "Т+: А2-Облигации - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 137, "board_group_id": 58, "engine_id": 1, "market_id": 2, "boardid": "TQNO", "board_title": "Т+: Б-Облигации - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 138, "board_group_id": 58, "engine_id": 1, "market_id": 2, "boardid": "TQOV", "board_title": "Т+: В-Облигации - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 139, "board_group_id": 58, "engine_id": 1, "market_id": 2, "boardid": "TQNB", "board_title": "Т+: Облигации внесписочные - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 140, "board_group_id": 58, "engine_id": 1, "market_id": 2, "boardid": "TQUS", "board_title": "Т+: Облигации внеспис. в ин.валюте - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 349, "board_group_id": 58, "engine_id": 1, "market_id": 2, "boardid": "TQCB", "board_title": "Т+: Облигации - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 361, "board_group_id": 58, "engine_id": 1, "market_id": 2, "boardid": "TQRD", "board_title": "Т+: Облигации Д - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 377, "board_group_id": 58, "engine_id": 1, "market_id": 2, "boardid": "TQIR", "board_title": "Т+ Облигации ПИР - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 226, "board_group_id": 193, "engine_id": 1, "market_id": 2, "boardid": "TQOD", "board_title": "Т+: Облигации (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 363, "board_group_id": 193, "engine_id": 1, "market_id": 2, "boardid": "TQUD", "board_title": "Т+: Облигации Д (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 383, "board_group_id": 193, "engine_id": 1, "market_id": 2, "boardid": "TQIU", "board_title": "Т+: Облигации ПИР (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 179, "board_group_id": 68, "engine_id": 1, "market_id": 2, "boardid": "TQTC", "board_title": "T+: ETC - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 8, "board_group_id": 7, "engine_id": 1, "market_id": 2, "boardid": "EQOB", "board_title": "Т0 Облигации - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 9, "board_group_id": 7, "engine_id": 1, "market_id": 2, "boardid": "EQOS", "board_title": "Основной режим: А2-Облигации - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 7, "board_group_id": 7, "engine_id": 1, "market_id": 2, "boardid": "EQNO", "board_title": "Основной режим: Б-Облигации - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 29, "board_group_id": 7, "engine_id": 1, "market_id": 2, "boardid": "EQOV", "board_title": "Основной режим: В-Облигации - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 93, "board_group_id": 7, "engine_id": 1, "market_id": 2, "boardid": "EQDB", "board_title": "Основной режим: Облигации Д - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 6, "board_group_id": 7, "engine_id": 1, "market_id": 2, "boardid": "EQNB", "board_title": "Основной режим: Облигации внесписочные - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 88, "board_group_id": 7, "engine_id": 1, "market_id": 2, "boardid": "EQUS", "board_title": "Основной режим: Облигации внеспис. в ин.валюте - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 165, "board_group_id": 7, "engine_id": 1, "market_id": 2, "boardid": "EQEO", "board_title": "Основной режим: Облигации (EUR) - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 119, "board_group_id": 105, "engine_id": 1, "market_id": 2, "boardid": "SPOB", "board_title": "Поставка по ОФЗ", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 176, "board_group_id": 69, "engine_id": 1, "market_id": 2, "boardid": "EQTC", "board_title": "T0 ETC - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 37, "board_group_id": 67, "engine_id": 1, "market_id": 2, "boardid": "EQEU", "board_title": "Облигации (USD) - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 228, "board_group_id": 67, "engine_id": 1, "market_id": 2, "boardid": "EQGO", "board_title": "Облигации (GBP) - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 229, "board_group_id": 67, "engine_id": 1, "market_id": 2, "boardid": "EQYO", "board_title": "Облигации (CNY) - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 122, "board_group_id": 122, "engine_id": 1, "market_id": 2, "boardid": "AUBB", "board_title": "Выкуп: Аукцион - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 121, "board_group_id": 123, "engine_id": 1, "market_id": 2, "boardid": "AUCT", "board_title": "Размещение: Аукцион - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 227, "board_group_id": 77, "engine_id": 1, "market_id": 2, "boardid": "TQDB", "board_title": "Крупные пакеты: Облигации - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 357, "board_group_id": 207, "engine_id": 1, "market_id": 2, "boardid": "TQOE", "board_title": "Т+: Облигации (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 365, "board_group_id": 207, "engine_id": 1, "market_id": 2, "boardid": "TQED", "board_title": "Т+: Облигации Д (EUR) - безадрес", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 389, "board_group_id": 207, "engine_id": 1, "market_id": 2, "boardid": "TQIE", "board_title": "Т+: Облигации ПИР (EUR) - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 323, "board_group_id": 167, "engine_id": 1, "market_id": 2, "boardid": "TQDU", "board_title": "Крупные пакеты – Облигации (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1101, "board_group_id": 245, "engine_id": 1, "market_id": 2, "boardid": "TQOY", "board_title": "Т+: Облигации (CNY) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 395, "board_group_id": 245, "engine_id": 1, "market_id": 2, "boardid": "TQIY", "board_title": "Т+: Облигации ПИР (CNY) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 407, "board_group_id": 257, "engine_id": 1, "market_id": 2, "boardid": "PACT", "board_title": "Аукцион: адресные заявки", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 24, "board_group_id": 201, "engine_id": 1, "market_id": 3, "boardid": "RPMO", "board_title": "РЕПО-М - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 1},
{"id": 34, "board_group_id": 1, "engine_id": 1, "market_id": 3, "boardid": "RPEQ", "board_title": "РЕПО: Акции и паи - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 23, "board_group_id": 95, "engine_id": 1, "market_id": 3, "boardid": "RPMA", "board_title": "РЕПО c акциями - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 35, "board_group_id": 94, "engine_id": 1, "market_id": 3, "boardid": "RPEU", "board_title": "РЕПО в ин. валюте (USD) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 162, "board_group_id": 94, "engine_id": 1, "market_id": 3, "boardid": "RPUA", "board_title": "РЕПО c акциями (USD) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 163, "board_group_id": 94, "engine_id": 1, "market_id": 3, "boardid": "RPUO", "board_title": "РЕПО c облигациями (USD) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 164, "board_group_id": 90, "engine_id": 1, "market_id": 3, "boardid": "RPEO", "board_title": "РЕПО в ин. валюте (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 254, "board_group_id": 2, "engine_id": 1, "market_id": 3, "boardid": "RPEY", "board_title": "РЕПО в ин.валюте (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 238, "board_group_id": 2, "engine_id": 1, "market_id": 3, "boardid": "RPGO", "board_title": "РЕПО c облигациями (GBP) - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 96, "board_group_id": 31, "engine_id": 1, "market_id": 3, "boardid": "RPCC", "board_title": "РЕПО с ЦК - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 154, "board_group_id": 193, "engine_id": 1, "market_id": 4, "boardid": "PTEU", "board_title": "РПС с ЦК: Облигации (USD) - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 173, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTIF", "board_title": "РПС с ЦК: Паи - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 175, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTTC", "board_title": "РПС с ЦК: ETC - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 174, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTTF", "board_title": "РПС с ЦК: ETF - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 142, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTEQ", "board_title": "РПС с ЦК: Акции и ДР - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 143, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTES", "board_title": "РПС С ЦК: А2-Акции и паи - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 144, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTNL", "board_title": "РПС С ЦК: Б-Акции и паи - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 145, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTLV", "board_title": "РПС С ЦК: В-Акции и ДР - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 146, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTLI", "board_title": "РПС С ЦК: И-Акции - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 147, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTNE", "board_title": "РПС С ЦК: Акции, паи и ДР внесписочные - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 150, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTNO", "board_title": "РПС С ЦК: Б-Облигации - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 153, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTUS", "board_title": "РПС С ЦК: Облигации в ин.валюте - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 161, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTDE", "board_title": "РПС с ЦК: Акции Д - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 405, "board_group_id": 59, "engine_id": 1, "market_id": 4, "boardid": "PTPI", "board_title": "РПС с ЦК: Акции ПИР - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 234, "board_group_id": 74, "engine_id": 1, "market_id": 4, "boardid": "PSTD", "board_title": "РПС: ETF (USD) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 437, "board_group_id": 74, "engine_id": 1, "market_id": 4, "boardid": "PSFD", "board_title": "РПС: ПАИ (USD) - адресн.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 439, "board_group_id": 74, "engine_id": 1, "market_id": 4, "boardid": "PSPD", "board_title": "РПС: Акции ПИР (USD) - адресн.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 170, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSIF", "board_title": "РПС: Паи - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 1},
{"id": 172, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSTC", "board_title": "РПС: ETC - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 171, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSTF", "board_title": "РПС: ETF - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 1},
{"id": 11, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSEQ", "board_title": "РПС: Акции - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 1},
{"id": 12, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSES", "board_title": "РПС: А2-Акции и паи - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 15, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSNL", "board_title": "РПС: Б-Акции и паи - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 32, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSLV", "board_title": "РПС: В-Акции и ДР - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 118, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSDE", "board_title": "РПС: Акции Д - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 31, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSLI", "board_title": "РПС: И-Акции - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 14, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSNE", "board_title": "РПС: Акции, паи и ДР внесписочные - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 18, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSOS", "board_title": "РПС: А2-Облигации - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 16, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSNO", "board_title": "РПС: Б-Облигации - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 33, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSOV", "board_title": "РПС: В-Облигации - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 13, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSNB", "board_title": "РПС: Облигации внесписочные - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 89, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSUS", "board_title": "РПС: Облигации в ин.валюте - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 403, "board_group_id": 8, "engine_id": 1, "market_id": 4, "boardid": "PSPI", "board_title": "РПС: Акции ПИР - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 235, "board_group_id": 106, "engine_id": 1, "market_id": 4, "boardid": "PSGO", "board_title": "РПС: Облигации (GBP) - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 98, "board_group_id": 107, "engine_id": 1, "market_id": 4, "boardid": "PSAU", "board_title": "Размещение - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 99, "board_group_id": 107, "engine_id": 1, "market_id": 4, "boardid": "PAUS", "board_title": "Размещение (USD) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 159, "board_group_id": 107, "engine_id": 1, "market_id": 4, "boardid": "PAEU", "board_title": "Размещение (EUR) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 237, "board_group_id": 107, "engine_id": 1, "market_id": 4, "boardid": "PACY", "board_title": "Размещение (CNY) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 169, "board_group_id": 107, "engine_id": 1, "market_id": 4, "boardid": "PAGB", "board_title": "Размещение (GBP) - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 120, "board_group_id": 108, "engine_id": 1, "market_id": 4, "boardid": "PSBB", "board_title": "Выкуп - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 278, "board_group_id": 121, "engine_id": 1, "market_id": 4, "boardid": "PSBE", "board_title": "Выкуп (EUR) - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 282, "board_group_id": 126, "engine_id": 1, "market_id": 4, "boardid": "OTCB", "board_title": "Анонимный РПС - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 353, "board_group_id": 203, "engine_id": 1, "market_id": 4, "boardid": "OTCU", "board_title": "Анонимный РПС (USD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 355, "board_group_id": 205, "engine_id": 1, "market_id": 4, "boardid": "OTCE", "board_title": "Анонимный РПС (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 231, "board_group_id": 73, "engine_id": 1, "market_id": 4, "boardid": "PTTD", "board_title": "РПС с ЦК: ETF (USD) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 433, "board_group_id": 73, "engine_id": 1, "market_id": 4, "boardid": "PTFD", "board_title": "РПС с ЦК: Паи (USD) - адресн.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 435, "board_group_id": 73, "engine_id": 1, "market_id": 4, "boardid": "PTPD", "board_title": "РПС с ЦК: Акции ПИР (USD) - адресн.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 277, "board_group_id": 124, "engine_id": 1, "market_id": 4, "boardid": "PSBU", "board_title": "Выкуп (USD) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 359, "board_group_id": 209, "engine_id": 1, "market_id": 4, "boardid": "PTOE", "board_title": "РПС с ЦК: Облигации (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 369, "board_group_id": 209, "engine_id": 1, "market_id": 4, "boardid": "PTED", "board_title": "РПС с ЦК: Д Облигации (EUR) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 393, "board_group_id": 209, "engine_id": 1, "market_id": 4, "boardid": "PTIE", "board_title": "РПС с ЦК: Облигации ПИР (EUR) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 316, "board_group_id": 160, "engine_id": 1, "market_id": 4, "boardid": "PSSE", "board_title": "РПС: Акции и ДР (расч. в EUR) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 317, "board_group_id": 160, "engine_id": 1, "market_id": 4, "boardid": "PSTE", "board_title": "РПС: ETF (расч. в EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 449, "board_group_id": 160, "engine_id": 1, "market_id": 4, "boardid": "PSFE", "board_title": "РПС: ПАИ (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 451, "board_group_id": 160, "engine_id": 1, "market_id": 4, "boardid": "PSPE", "board_title": "РПС: Акции ПИР (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 318, "board_group_id": 163, "engine_id": 1, "market_id": 4, "boardid": "PTSE", "board_title": "РПС с ЦК: Акции и ДР (EUR) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 319, "board_group_id": 163, "engine_id": 1, "market_id": 4, "boardid": "PTTE", "board_title": "РПС с ЦК: ETF (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 445, "board_group_id": 163, "engine_id": 1, "market_id": 4, "boardid": "PTFE", "board_title": "РПС с ЦК: Паи (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 447, "board_group_id": 163, "engine_id": 1, "market_id": 4, "boardid": "PTPE", "board_title": "РПС с ЦК: Акции ПИР (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 148, "board_group_id": 282, "engine_id": 1, "market_id": 4, "boardid": "PTOB", "board_title": "РПС с ЦК: Облигации - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 149, "board_group_id": 282, "engine_id": 1, "market_id": 4, "boardid": "PTOS", "board_title": "РПС С ЦК: А2-Облигации - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 151, "board_group_id": 282, "engine_id": 1, "market_id": 4, "boardid": "PTOV", "board_title": "РПС С ЦК: В-Облигации - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 152, "board_group_id": 282, "engine_id": 1, "market_id": 4, "boardid": "PTNB", "board_title": "РПС С ЦК: Облигации внесписочные - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 367, "board_group_id": 282, "engine_id": 1, "market_id": 4, "boardid": "PTDB", "board_title": "РПС с ЦК: Д Облигации - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 381, "board_group_id": 282, "engine_id": 1, "market_id": 4, "boardid": "PTIR", "board_title": "РПС с ЦК: Облигации ПИР - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 232, "board_group_id": 283, "engine_id": 1, "market_id": 4, "boardid": "PTOD", "board_title": "РПС с ЦК: Облигации (USD) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 371, "board_group_id": 283, "engine_id": 1, "market_id": 4, "boardid": "PTUD", "board_title": "РПС с ЦК: Д Облигации (USD) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 387, "board_group_id": 283, "engine_id": 1, "market_id": 4, "boardid": "PTIU", "board_title": "РПС с ЦК: Облигации ПИР (USD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 17, "board_group_id": 284, "engine_id": 1, "market_id": 4, "boardid": "PSOB", "board_title": "РПС: Облигации - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 92, "board_group_id": 284, "engine_id": 1, "market_id": 4, "boardid": "PSDB", "board_title": "РПС: Облигации Д - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 379, "board_group_id": 284, "engine_id": 1, "market_id": 4, "boardid": "PSIR", "board_title": "РПС: Облигации ПИР - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 30, "board_group_id": 285, "engine_id": 1, "market_id": 4, "boardid": "PSEU", "board_title": "РПС: Облигации (USD) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 375, "board_group_id": 285, "engine_id": 1, "market_id": 4, "boardid": "PSUD", "board_title": "РПС: Облигации Д (USD) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 385, "board_group_id": 285, "engine_id": 1, "market_id": 4, "boardid": "PSIU", "board_title": "РПС: Облигации ПИР (USD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 160, "board_group_id": 286, "engine_id": 1, "market_id": 4, "boardid": "PSEO", "board_title": "РПС: Облигации (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 373, "board_group_id": 286, "engine_id": 1, "market_id": 4, "boardid": "PSED", "board_title": "РПС: Облигации Д (EUR) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 391, "board_group_id": 286, "engine_id": 1, "market_id": 4, "boardid": "PSIE", "board_title": "РПС: Облигации ПИР (EUR) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 236, "board_group_id": 247, "engine_id": 1, "market_id": 4, "boardid": "PSYO", "board_title": "РПС: Облигации (CNY) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 397, "board_group_id": 247, "engine_id": 1, "market_id": 4, "boardid": "PSIY", "board_title": "РПС: Облигации ПИР (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 399, "board_group_id": 249, "engine_id": 1, "market_id": 4, "boardid": "PTIY", "board_title": "РПС с ЦК: Облигации ПИР (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1151, "board_group_id": 249, "engine_id": 1, "market_id": 4, "boardid": "PTOY", "board_title": "РПС с ЦК: Облигации (CNY) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1219, "board_group_id": 1218, "engine_id": 1, "market_id": 4, "boardid": "PSTY", "board_title": "РПС: ПАИ (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1220, "board_group_id": 1218, "engine_id": 1, "market_id": 4, "boardid": "PSPY", "board_title": "РПС: Акции ПИР (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1222, "board_group_id": 1221, "engine_id": 1, "market_id": 4, "boardid": "PTTY", "board_title": "РПС с ЦК: Паи (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1223, "board_group_id": 1221, "engine_id": 1, "market_id": 4, "boardid": "PTPY", "board_title": "РПС с ЦК: Акции ПИР (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1242, "board_group_id": 1241, "engine_id": 1, "market_id": 4, "boardid": "PSTH", "board_title": "РПС: ПАИ (HKD) - адресн.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1243, "board_group_id": 1241, "engine_id": 1, "market_id": 4, "boardid": "PSPH", "board_title": "РПС: Акции ПИР (HKD) - адресн.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1245, "board_group_id": 1244, "engine_id": 1, "market_id": 4, "boardid": "PTTH", "board_title": "РПС с ЦК: Паи (HKD) - адресн.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1246, "board_group_id": 1244, "engine_id": 1, "market_id": 4, "boardid": "PTPH", "board_title": "РПС с ЦК: Акции ПИР (HKD) - адресн.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 97, "board_group_id": 32, "engine_id": 1, "market_id": 4, "boardid": "PSCC", "board_title": "РПС с ЦК - адрес.", "is_traded": 0, "has_candles": 0, "is_primary": 0},
{"id": 44, "board_group_id": 9, "engine_id": 1, "market_id": 5, "boardid": "SNDX", "board_title": "Индексы фондового рынка", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 102, "board_group_id": 9, "engine_id": 1, "market_id": 5, "boardid": "RTSI", "board_title": "Индексы РТС", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 265, "board_group_id": 104, "engine_id": 1, "market_id": 5, "boardid": "INAV", "board_title": "INAV", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 312, "board_group_id": 155, "engine_id": 1, "market_id": 5, "boardid": "MMIX", "board_title": "Money Market IndeX", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1029, "board_group_id": 1028, "engine_id": 1, "market_id": 5, "boardid": "AGRO", "board_title": "Индексы НТБ", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1154, "board_group_id": 1153, "engine_id": 1, "market_id": 5, "boardid": "INPF", "board_title": "Ценовой фиксинг", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 500, "board_group_id": 287, "engine_id": 1, "market_id": 5, "boardid": "SDII", "board_title": "Индексы СПФИ", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 104, "board_group_id": 36, "engine_id": 1, "market_id": 23, "boardid": "STMR", "board_title": "Standard: дневная сессия - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 105, "board_group_id": 36, "engine_id": 1, "market_id": 23, "boardid": "SDMR", "board_title": "Standard: вечерняя сессия - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 108, "board_group_id": 41, "engine_id": 1, "market_id": 23, "boardid": "STAD", "board_title": "Standard: дневная сессия - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 109, "board_group_id": 41, "engine_id": 1, "market_id": 23, "boardid": "SDAD", "board_title": "Standard: вечерняя сессия - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 106, "board_group_id": 40, "engine_id": 1, "market_id": 23, "boardid": "STRP", "board_title": "Standard: сделки репо, дневная сессия - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 107, "board_group_id": 40, "engine_id": 1, "market_id": 23, "boardid": "SDRP", "board_title": "Standard: сделки репо, вечерняя сессия - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 112, "board_group_id": 43, "engine_id": 1, "market_id": 25, "boardid": "CLMR", "board_title": "Classica - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 113, "board_group_id": 44, "engine_id": 1, "market_id": 25, "boardid": "CLAD", "board_title": "Classica - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 239, "board_group_id": 92, "engine_id": 1, "market_id": 27, "boardid": "EQRD", "board_title": "РЕПО с ЦК 1 день (USD) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 240, "board_group_id": 93, "engine_id": 1, "market_id": 27, "boardid": "EQRE", "board_title": "РЕПО с ЦК 1 день (EUR) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 241, "board_group_id": 76, "engine_id": 1, "market_id": 27, "boardid": "EQWP", "board_title": "РЕПО с ЦК 7 дн. - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 245, "board_group_id": 78, "engine_id": 1, "market_id": 27, "boardid": "EQWD", "board_title": "РЕПО с ЦК 7 дней (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 246, "board_group_id": 79, "engine_id": 1, "market_id": 27, "boardid": "EQWE", "board_title": "РЕПО с ЦК 7 дней (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 123, "board_group_id": 50, "engine_id": 1, "market_id": 27, "boardid": "EQRP", "board_title": "РЕПО с ЦК 1 день - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 298, "board_group_id": 142, "engine_id": 1, "market_id": 27, "boardid": "EQMP", "board_title": "РЕПО с ЦК 1 мес.(RUB) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 299, "board_group_id": 143, "engine_id": 1, "market_id": 27, "boardid": "EQMD", "board_title": "РЕПО с ЦК 1 мес. (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 300, "board_group_id": 144, "engine_id": 1, "market_id": 27, "boardid": "EQME", "board_title": "РЕПО с ЦК 1 мес. (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 301, "board_group_id": 145, "engine_id": 1, "market_id": 27, "boardid": "EQTP", "board_title": "РЕПО с ЦК 3 мес. (RUB) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 302, "board_group_id": 146, "engine_id": 1, "market_id": 27, "boardid": "ETQD", "board_title": "РЕПО с ЦК 3 мес. (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 303, "board_group_id": 147, "engine_id": 1, "market_id": 27, "boardid": "EQTE", "board_title": "РЕПО с ЦК 3 мес. (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 304, "board_group_id": 148, "engine_id": 1, "market_id": 27, "boardid": "LIQR", "board_title": "РЕПО с ЦК: Урегулирование - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 309, "board_group_id": 152, "engine_id": 1, "market_id": 27, "boardid": "EQRY", "board_title": "РЕПО с ЦК 1 день (CNY) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 310, "board_group_id": 153, "engine_id": 1, "market_id": 27, "boardid": "PSRY", "board_title": "РЕПО с ЦК (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1117, "board_group_id": 1116, "engine_id": 1, "market_id": 27, "boardid": "EQWY", "board_title": "РЕПО с ЦК 7 дней (CNY) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1119, "board_group_id": 1118, "engine_id": 1, "market_id": 27, "boardid": "EQMY", "board_title": "РЕПО с ЦК 1 мес. (CNY) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1121, "board_group_id": 1120, "engine_id": 1, "market_id": 27, "boardid": "EQTY", "board_title": "РЕПО с ЦК 3 мес. (CNY) - безадрес", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 125, "board_group_id": 65, "engine_id": 1, "market_id": 27, "boardid": "PSRP", "board_title": "РЕПО с ЦК - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 242, "board_group_id": 91, "engine_id": 1, "market_id": 27, "boardid": "PSRD", "board_title": "РЕПО с ЦК (USD) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 243, "board_group_id": 96, "engine_id": 1, "market_id": 27, "boardid": "PSRE", "board_title": "РЕПО с ЦК (EUR) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 325, "board_group_id": 169, "engine_id": 1, "market_id": 27, "boardid": "FKRP", "board_title": "Аукцион с ЦК 1 день - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 327, "board_group_id": 171, "engine_id": 1, "market_id": 27, "boardid": "FKOW", "board_title": "Аукцион с ЦК 1 неделя - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 329, "board_group_id": 173, "engine_id": 1, "market_id": 27, "boardid": "FKSW", "board_title": "Аукцион с ЦК 2 недели - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 499, "board_group_id": 281, "engine_id": 1, "market_id": 27, "boardid": "FKFW", "board_title": "Аукцион с ЦК 5 недель - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 331, "board_group_id": 175, "engine_id": 1, "market_id": 27, "boardid": "FKOM", "board_title": "Аукцион с ЦК 1 месяц - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 333, "board_group_id": 177, "engine_id": 1, "market_id": 27, "boardid": "FKSM", "board_title": "Аукцион с ЦК 2 месяца - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 335, "board_group_id": 179, "engine_id": 1, "market_id": 27, "boardid": "FKTM", "board_title": "Аукцион с ЦК 3 месяца - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 337, "board_group_id": 181, "engine_id": 1, "market_id": 27, "boardid": "FKUM", "board_title": "Аукцион с ЦК 6 месяцев - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 339, "board_group_id": 183, "engine_id": 1, "market_id": 27, "boardid": "FKOY", "board_title": "Аукцион с ЦК 1 год - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 501, "board_group_id": 288, "engine_id": 1, "market_id": 27, "boardid": "FRRP", "board_title": "Аукцион РЕПО с ЦК 1 день - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 502, "board_group_id": 289, "engine_id": 1, "market_id": 27, "boardid": "FROW", "board_title": "Аукцион РЕПО с ЦК 1 неделя - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 513, "board_group_id": 296, "engine_id": 1, "market_id": 27, "boardid": "FRSW", "board_title": "Аукцион РЕПО с ЦК 2 недели - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 514, "board_group_id": 297, "engine_id": 1, "market_id": 27, "boardid": "FRFW", "board_title": "Аукцион РЕПО с ЦК 5 недель - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 503, "board_group_id": 290, "engine_id": 1, "market_id": 27, "boardid": "FROM", "board_title": "Аукцион РЕПО с ЦК 1 месяц - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 504, "board_group_id": 291, "engine_id": 1, "market_id": 27, "boardid": "FRTM", "board_title": "Аукцион РЕПО с ЦК 3 месяца - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1248, "board_group_id": 1247, "engine_id": 1, "market_id": 27, "boardid": "FSRP", "board_title": "Аукцион обр.РЕПО с ЦК 1 день - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1250, "board_group_id": 1249, "engine_id": 1, "market_id": 27, "boardid": "FSOW", "board_title": "Аукцион обр.РЕПО с ЦК 1 неделя - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1252, "board_group_id": 1251, "engine_id": 1, "market_id": 27, "boardid": "FSSW", "board_title": "Аукцион обр.РЕПО с ЦК 2 недели - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1254, "board_group_id": 1253, "engine_id": 1, "market_id": 27, "boardid": "FSOM", "board_title": "Аукцион обр.РЕПО с ЦК 1 месяц - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1256, "board_group_id": 1255, "engine_id": 1, "market_id": 27, "boardid": "FSFW", "board_title": "Аукцион обр.РЕПО с ЦК 5 недель - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 167, "board_group_id": 63, "engine_id": 1, "market_id": 28, "boardid": "TQQI", "board_title": "Т+: Для квал. инвесторов - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 155, "board_group_id": 60, "engine_id": 1, "market_id": 28, "boardid": "EQQI", "board_title": "Основной режим: Для квал. инвесторов - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 156, "board_group_id": 61, "engine_id": 1, "market_id": 28, "boardid": "PSQI", "board_title": "РПС: Для квал. инвесторов - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 168, "board_group_id": 64, "engine_id": 1, "market_id": 28, "boardid": "PTQI", "board_title": "РПС с ЦК: Для квал. инвесторов - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 157, "board_group_id": 62, "engine_id": 1, "market_id": 28, "boardid": "RPQI", "board_title": "РЕПО: Для квал. инвесторов - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 166, "board_group_id": 62, "engine_id": 1, "market_id": 28, "boardid": "RPUQ", "board_title": "РЕПО: Для квал. инвесторов (USD) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 255, "board_group_id": 87, "engine_id": 1, "market_id": 28, "boardid": "TQQD", "board_title": "Т+: Для квал. инвесторов (USD) - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 183, "board_group_id": 71, "engine_id": 1, "market_id": 29, "boardid": "SOTC", "board_title": "Репортинг внебиржевых сделок (6264-У)", "is_traded": 1, "has_candles": 0, "is_primary": 1},
{"id": 244, "board_group_id": 72, "engine_id": 1, "market_id": 33, "boardid": "MXBD", "board_title": "MOEX Board", "is_traded": 1, "has_candles": 0, "is_primary": 1},
{"id": 258, "board_group_id": 97, "engine_id": 1, "market_id": 35, "boardid": "TDEP", "board_title": "Депозиты с ЦК - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 259, "board_group_id": 98, "engine_id": 1, "market_id": 35, "boardid": "NDEP", "board_title": "Депозиты с ЦК - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 266, "board_group_id": 109, "engine_id": 1, "market_id": 35, "boardid": "NDPU", "board_title": "Депозиты с ЦК (USD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 292, "board_group_id": 136, "engine_id": 1, "market_id": 35, "boardid": "NDPE", "board_title": "Депозиты с ЦК (EUR) - адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 267, "board_group_id": 110, "engine_id": 1, "market_id": 35, "boardid": "TDPU", "board_title": "Депозиты с ЦК (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 293, "board_group_id": 137, "engine_id": 1, "market_id": 35, "boardid": "TDPE", "board_title": "Депозиты с ЦК (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1143, "board_group_id": 1142, "engine_id": 1, "market_id": 35, "boardid": "TDPY", "board_title": "Депозиты с ЦК (CNY) - безадрес. ", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1145, "board_group_id": 1144, "engine_id": 1, "market_id": 35, "boardid": "NDPY", "board_title": "Депозиты с ЦК (CNY) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 341, "board_group_id": 185, "engine_id": 1, "market_id": 35, "boardid": "ADEP", "board_title": "Депозиты с ЦК - Аукцион", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 279, "board_group_id": 120, "engine_id": 1, "market_id": 36, "boardid": "LIQB", "board_title": "Продажа обеспечения бирж.рынок - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 1083, "board_group_id": 1082, "engine_id": 1, "market_id": 36, "boardid": "CIQB", "board_title": "Урегулирование с ЦК Нерезиденты - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 253, "board_group_id": 86, "engine_id": 1, "market_id": 46, "boardid": "GCRP", "board_title": "РЕПО с ЦК с КСУ 1 день - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 250, "board_group_id": 83, "engine_id": 1, "market_id": 46, "boardid": "GCOW", "board_title": "РЕПО с ЦК с КСУ 7 дн. - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 247, "board_group_id": 80, "engine_id": 1, "market_id": 46, "boardid": "GCSW", "board_title": "РЕПО с ЦК с КСУ 14 дн. - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 251, "board_group_id": 84, "engine_id": 1, "market_id": 46, "boardid": "GCOM", "board_title": "РЕПО с ЦК с КСУ 1 месяц - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 248, "board_group_id": 81, "engine_id": 1, "market_id": 46, "boardid": "GCSM", "board_title": "РЕПО с ЦК с КСУ 2 месяца - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 252, "board_group_id": 85, "engine_id": 1, "market_id": 46, "boardid": "GCTM", "board_title": "РЕПО с ЦК с КСУ 3 месяца - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 264, "board_group_id": 103, "engine_id": 1, "market_id": 46, "boardid": "GCUM", "board_title": "РЕПО с ЦК с КСУ 6 мес. - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 263, "board_group_id": 102, "engine_id": 1, "market_id": 46, "boardid": "GCOY", "board_title": "РЕПО с ЦК с КСУ 1 год - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 249, "board_group_id": 82, "engine_id": 1, "market_id": 46, "boardid": "PSGC", "board_title": "РЕПО с ЦК с КСУ - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 268, "board_group_id": 111, "engine_id": 1, "market_id": 46, "boardid": "GURP", "board_title": "РЕПО с ЦК с КСУ 1 день (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 269, "board_group_id": 112, "engine_id": 1, "market_id": 46, "boardid": "GUOW", "board_title": "РЕПО с ЦК с КСУ 7 дн. (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 270, "board_group_id": 113, "engine_id": 1, "market_id": 46, "boardid": "GUSW", "board_title": "РЕПО с ЦК с КСУ 14 дн. (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 271, "board_group_id": 114, "engine_id": 1, "market_id": 46, "boardid": "GUOM", "board_title": "РЕПО с ЦК с КСУ 1 месяц (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 272, "board_group_id": 115, "engine_id": 1, "market_id": 46, "boardid": "GUSM", "board_title": "РЕПО с ЦК с КСУ 2 месяца (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 273, "board_group_id": 116, "engine_id": 1, "market_id": 46, "boardid": "GUTM", "board_title": "РЕПО с ЦК с КСУ 3 месяца (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 274, "board_group_id": 117, "engine_id": 1, "market_id": 46, "boardid": "GUUM", "board_title": "РЕПО с ЦК с КСУ 6 месяцев (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 275, "board_group_id": 118, "engine_id": 1, "market_id": 46, "boardid": "GUOY", "board_title": "РЕПО с ЦК с КСУ 1 год (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 276, "board_group_id": 119, "engine_id": 1, "market_id": 46, "boardid": "PUGC", "board_title": "РЕПО с ЦК с КСУ (USD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 283, "board_group_id": 127, "engine_id": 1, "market_id": 46, "boardid": "GERP", "board_title": "РЕПО с ЦК с КСУ 1 день (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 284, "board_group_id": 128, "engine_id": 1, "market_id": 46, "boardid": "GEOW", "board_title": "РЕПО с ЦК с КСУ 7 дн. (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 285, "board_group_id": 129, "engine_id": 1, "market_id": 46, "boardid": "GESW", "board_title": "РЕПО с ЦК с КСУ 14 дн. (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 286, "board_group_id": 130, "engine_id": 1, "market_id": 46, "boardid": "GEOM", "board_title": "РЕПО с ЦК с КСУ 1 месяц (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 287, "board_group_id": 131, "engine_id": 1, "market_id": 46, "boardid": "GESM", "board_title": "РЕПО с ЦК с КСУ 2 месяца (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 288, "board_group_id": 132, "engine_id": 1, "market_id": 46, "boardid": "GETM", "board_title": "РЕПО с ЦК с КСУ 3 месяца (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 289, "board_group_id": 133, "engine_id": 1, "market_id": 46, "boardid": "GEUM", "board_title": "РЕПО с ЦК с КСУ 6 месяцев (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 290, "board_group_id": 134, "engine_id": 1, "market_id": 46, "boardid": "GEOY", "board_title": "РЕПО с ЦК с КСУ 1 год (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 291, "board_group_id": 135, "engine_id": 1, "market_id": 46, "boardid": "PEGC", "board_title": "РЕПО с ЦК с КСУ (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 343, "board_group_id": 187, "engine_id": 1, "market_id": 46, "boardid": "GCNM", "board_title": "РЕПО с ЦК с КСУ 9 месяцев - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 345, "board_group_id": 189, "engine_id": 1, "market_id": 46, "boardid": "GUNM", "board_title": "РЕПО с ЦК с КСУ 9 мес. (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 347, "board_group_id": 191, "engine_id": 1, "market_id": 46, "boardid": "GENM", "board_title": "РЕПО с ЦК с КСУ 9 мес. (EUR) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1123, "board_group_id": 1122, "engine_id": 1, "market_id": 46, "boardid": "GYRP", "board_title": "РЕПО с ЦК с КСУ 1 день (CNY) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1125, "board_group_id": 1124, "engine_id": 1, "market_id": 46, "boardid": "GYOW", "board_title": "РЕПО с ЦК с КСУ 7 дней (CNY) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1127, "board_group_id": 1126, "engine_id": 1, "market_id": 46, "boardid": "GYSW", "board_title": "РЕПО с ЦК с КСУ 14 дней (CNY) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1129, "board_group_id": 1128, "engine_id": 1, "market_id": 46, "boardid": "GYOM", "board_title": "РЕПО с ЦК с КСУ 1 месяц (CNY) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1131, "board_group_id": 1130, "engine_id": 1, "market_id": 46, "boardid": "GYSM", "board_title": "РЕПО с ЦК с КСУ 2 месяца (CNY) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1133, "board_group_id": 1132, "engine_id": 1, "market_id": 46, "boardid": "GYTM", "board_title": "РЕПО с ЦК с КСУ 3 месяца (CNY) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1135, "board_group_id": 1134, "engine_id": 1, "market_id": 46, "boardid": "GYUM", "board_title": "РЕПО с ЦК с КСУ 6 месяцев (CNY) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1137, "board_group_id": 1136, "engine_id": 1, "market_id": 46, "boardid": "GYNM", "board_title": "РЕПО с ЦК с КСУ 9 месяцев (CNY) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1139, "board_group_id": 1138, "engine_id": 1, "market_id": 46, "boardid": "GYOY", "board_title": "РЕПО с ЦК с КСУ 1 год (CNY) - безадрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1141, "board_group_id": 1140, "engine_id": 1, "market_id": 46, "boardid": "PYGC", "board_title": "РЕПО с ЦК с КСУ (CNY) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1157, "board_group_id": 1156, "engine_id": 1, "market_id": 46, "boardid": "FCOW", "board_title": "РЕПО с ЦК с КСУ пл. 7 дней - безадрес. (RUSFAR)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1159, "board_group_id": 1158, "engine_id": 1, "market_id": 46, "boardid": "FCSW", "board_title": "РЕПО с ЦК с КСУ пл. 14 дней - безадрес. (RUSFAR)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1161, "board_group_id": 1160, "engine_id": 1, "market_id": 46, "boardid": "FCOM", "board_title": "РЕПО с ЦК с КСУ пл. 1 месяц - безадрес. (RUSFAR)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1163, "board_group_id": 1162, "engine_id": 1, "market_id": 46, "boardid": "FCSM", "board_title": "РЕПО с ЦК с КСУ пл. 2 месяца - безадрес. (RUSFAR)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1165, "board_group_id": 1164, "engine_id": 1, "market_id": 46, "boardid": "FCTM", "board_title": "РЕПО с ЦК с КСУ пл. 3 месяца - безадрес. (RUSFAR)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1167, "board_group_id": 1166, "engine_id": 1, "market_id": 46, "boardid": "FCUM", "board_title": "РЕПО с ЦК с КСУ пл. 6 месяца - безадрес. (RUSFAR)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1169, "board_group_id": 1168, "engine_id": 1, "market_id": 46, "boardid": "FCNM", "board_title": "РЕПО с ЦК с КСУ пл. 9 месяца - безадрес. (RUSFAR)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1171, "board_group_id": 1170, "engine_id": 1, "market_id": 46, "boardid": "FCOY", "board_title": "РЕПО с ЦК с КСУ пл. 1 год - безадрес. (RUSFAR)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1189, "board_group_id": 1188, "engine_id": 1, "market_id": 46, "boardid": "FYOW", "board_title": "РЕПО с ЦК с КСУ пл. 7 дней (CNY) - безадрес. (RUSFARCNY)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1191, "board_group_id": 1190, "engine_id": 1, "market_id": 46, "boardid": "FYSW", "board_title": "РЕПО с ЦК с КСУ пл. 14 дней (CNY) - безадрес. (RUSFARCNY)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1193, "board_group_id": 1192, "engine_id": 1, "market_id": 46, "boardid": "FYOM", "board_title": "РЕПО с ЦК с КСУ пл. 1 месяц (CNY) - безадрес. (RUSFARCNY)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1195, "board_group_id": 1194, "engine_id": 1, "market_id": 46, "boardid": "FYSM", "board_title": "РЕПО с ЦК с КСУ пл. 2 месяца (CNY) - безадрес. (RUSFARCNY)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1197, "board_group_id": 1196, "engine_id": 1, "market_id": 46, "boardid": "FYTM", "board_title": "РЕПО с ЦК с КСУ пл. 3 месяца (CNY) - безадрес. (RUSFARCNY)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1199, "board_group_id": 1198, "engine_id": 1, "market_id": 46, "boardid": "FYUM", "board_title": "РЕПО с ЦК с КСУ пл. 6 месяца (CNY) - безадрес. (RUSFARCNY)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1201, "board_group_id": 1200, "engine_id": 1, "market_id": 46, "boardid": "FYNM", "board_title": "РЕПО с ЦК с КСУ пл. 9 месяца (CNY) - безадрес. (RUSFARCNY)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1203, "board_group_id": 1202, "engine_id": 1, "market_id": 46, "boardid": "FYOY", "board_title": "РЕПО с ЦК с КСУ пл. 1 год (CNY) - безадрес. (RUSFARCNY)", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1230, "board_group_id": 1229, "engine_id": 1, "market_id": 47, "boardid": "FQBH", "board_title": "Т+: Ин.Акции и ДР (HKD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1231, "board_group_id": 1229, "engine_id": 1, "market_id": 47, "boardid": "FQDH", "board_title": "Т+: Ин.Акции ПИР (HKD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 415, "board_group_id": 265, "engine_id": 1, "market_id": 47, "boardid": "FQBR", "board_title": "Т+ Ин.Акции и ДР - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 417, "board_group_id": 265, "engine_id": 1, "market_id": 47, "boardid": "FQDE", "board_title": "Т+ Ин.Акции ПИР - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 224, "board_group_id": 292, "engine_id": 1, "market_id": 47, "boardid": "TQBD", "board_title": "Т+: Ин.Акции и ДР (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 508, "board_group_id": 292, "engine_id": 1, "market_id": 47, "boardid": "TQDD", "board_title": "Т+: Ин.Акции ПИР (USD) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1207, "board_group_id": 1206, "engine_id": 1, "market_id": 47, "boardid": "FQBY", "board_title": "Т+: Ин.Акции и ДР (CNY) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1208, "board_group_id": 1206, "engine_id": 1, "market_id": 47, "boardid": "FQDY", "board_title": "Т+: Ин.Акции ПИР (CNY) - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1233, "board_group_id": 1232, "engine_id": 1, "market_id": 49, "boardid": "FTSH", "board_title": "РПС с ЦК: Ин.Акции и ДР (HKD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1234, "board_group_id": 1232, "engine_id": 1, "market_id": 49, "boardid": "FTDH", "board_title": "РПС с ЦК: Ин.Акции ПИР (HKD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1236, "board_group_id": 1235, "engine_id": 1, "market_id": 49, "boardid": "FSSH", "board_title": "РПС: Ин.Акции (HKD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1237, "board_group_id": 1235, "engine_id": 1, "market_id": 49, "boardid": "FSDH", "board_title": "РПС: Ин.Акции ПИР (HKD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 419, "board_group_id": 267, "engine_id": 1, "market_id": 49, "boardid": "FTEQ", "board_title": "РПС с ЦК: Ин.Акции и ДР - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 421, "board_group_id": 267, "engine_id": 1, "market_id": 49, "boardid": "FTDE", "board_title": "РПС с ЦК: Ин.Акции ПИР - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 510, "board_group_id": 294, "engine_id": 1, "market_id": 49, "boardid": "PSSD", "board_title": "РПС: Ин.Акции (USD) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 509, "board_group_id": 294, "engine_id": 1, "market_id": 49, "boardid": "PSDD", "board_title": "РПС: Ин.Акции ПИР (USD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1210, "board_group_id": 1209, "engine_id": 1, "market_id": 49, "boardid": "FTSY", "board_title": "РПС с ЦК: Ин.Акции и ДР (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1211, "board_group_id": 1209, "engine_id": 1, "market_id": 49, "boardid": "FTDY", "board_title": "РПС с ЦК: Ин.Акции ПИР (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1213, "board_group_id": 1212, "engine_id": 1, "market_id": 49, "boardid": "FSSY", "board_title": "РПС: Ин.Акции (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1214, "board_group_id": 1212, "engine_id": 1, "market_id": 49, "boardid": "FSDY", "board_title": "РПС: Ин.Акции ПИР (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 423, "board_group_id": 269, "engine_id": 1, "market_id": 49, "boardid": "FSEQ", "board_title": "РПС: Ин.Акции - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 425, "board_group_id": 269, "engine_id": 1, "market_id": 49, "boardid": "FSDE", "board_title": "Ин.Акции ПИР - РПС - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 230, "board_group_id": 293, "engine_id": 1, "market_id": 49, "boardid": "PTSD", "board_title": "РПС с ЦК: Ин.Акции и ДР (USD) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 497, "board_group_id": 293, "engine_id": 1, "market_id": 49, "boardid": "PTDD", "board_title": "РПС с ЦК: Ин.Акции ПИР (USD) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 491, "board_group_id": 275, "engine_id": 1, "market_id": 54, "boardid": "CRER", "board_title": "Кредиты RUB - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 493, "board_group_id": 277, "engine_id": 1, "market_id": 54, "boardid": "CREU", "board_title": "Кредиты USD - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 495, "board_group_id": 279, "engine_id": 1, "market_id": 54, "boardid": "CREE", "board_title": "Кредиты EUR - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1147, "board_group_id": 1146, "engine_id": 1, "market_id": 54, "boardid": "CREY", "board_title": "Кредиты CNY - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1057, "board_group_id": 1056, "engine_id": 1, "market_id": 1015, "boardid": "CTEQ", "board_title": "РПС с ЦК Нерезиденты: Акции и ДР - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 1059, "board_group_id": 1058, "engine_id": 1, "market_id": 1015, "boardid": "CTSD", "board_title": "РПС с ЦК Нерезиденты: Акции и ДР (USD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1061, "board_group_id": 1060, "engine_id": 1, "market_id": 1015, "boardid": "CTSE", "board_title": "РПС с ЦК Нерезиденты: Акции и ДР (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1063, "board_group_id": 1062, "engine_id": 1, "market_id": 1015, "boardid": "CTOB", "board_title": "РПС с ЦК Нерезиденты: Облигации - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1065, "board_group_id": 1064, "engine_id": 1, "market_id": 1015, "boardid": "CTOY", "board_title": "РПС с ЦК Нерезиденты: Облигации (CNY) - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 1067, "board_group_id": 1066, "engine_id": 1, "market_id": 1015, "boardid": "CTOD", "board_title": "РПС с ЦК Нерезиденты: Облигации (USD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1069, "board_group_id": 1068, "engine_id": 1, "market_id": 1015, "boardid": "CTOE", "board_title": "РПС с ЦК Нерезиденты: Облигации (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1072, "board_group_id": 1071, "engine_id": 1, "market_id": 1017, "boardid": "CPMO", "board_title": "РЕПО-M Нерезиденты - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 1074, "board_group_id": 1073, "engine_id": 1, "market_id": 1017, "boardid": "CPEU", "board_title": "РЕПО-M Нерезиденты (USD) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1076, "board_group_id": 1075, "engine_id": 1, "market_id": 1017, "boardid": "CPEO", "board_title": "РЕПО-M Нерезиденты (EUR) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1078, "board_group_id": 1077, "engine_id": 1, "market_id": 1017, "boardid": "CPEY", "board_title": "РЕПО-M Нерезиденты (CNY) - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1081, "board_group_id": 1080, "engine_id": 1, "market_id": 1019, "boardid": "CIQR", "board_title": "Урегулирование РЕПО с ЦК Нерезиденты - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 19, "board_group_id": 10, "engine_id": 2, "market_id": 6, "boardid": "MAIN", "board_title": "ГЦБ", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 25, "board_group_id": 3, "engine_id": 2, "market_id": 7, "boardid": "RPDD", "board_title": "Сделки междилерского РЕПО", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 20, "board_group_id": 11, "engine_id": 2, "market_id": 8, "boardid": "NEGD", "board_title": "ГЦБ: Внесистемные сделки", "is_traded": 0, "has_candles": 0, "is_primary": 1},
{"id": 51, "board_group_id": 12, "engine_id": 2, "market_id": 9, "boardid": "GNDX", "board_title": "Индексы ГЦБ", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 21, "board_group_id": 13, "engine_id": 3, "market_id": 10, "boardid": "CETS", "board_title": "Системные сделки - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 351, "board_group_id": 13, "engine_id": 3, "market_id": 10, "boardid": "SDBP", "board_title": "Крупные сделки - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 52, "board_group_id": 13, "engine_id": 3, "market_id": 10, "boardid": "CURR", "board_title": "Дневная сессия", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 116, "board_group_id": 46, "engine_id": 3, "market_id": 10, "boardid": "CNGD", "board_title": "Внесистемные сделки- адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 308, "board_group_id": 151, "engine_id": 3, "market_id": 10, "boardid": "LICU", "board_title": "Внесистемные сделки урегулирования - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 261, "board_group_id": 100, "engine_id": 3, "market_id": 10, "boardid": "FIXS", "board_title": "Фиксинг системный - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 262, "board_group_id": 101, "engine_id": 3, "market_id": 10, "boardid": "FIXN", "board_title": "Фиксинг внесистемный- адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 306, "board_group_id": 149, "engine_id": 3, "market_id": 10, "boardid": "WAPS", "board_title": "Системные средневзвешенные - безадрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 307, "board_group_id": 150, "engine_id": 3, "market_id": 10, "boardid": "WAPN", "board_title": "Внесистемные средневзвешенные - адрес.", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 182, "board_group_id": 70, "engine_id": 3, "market_id": 10, "boardid": "AUCB", "board_title": "Аукцион ЦБР - адрес.", "is_traded": 1, "has_candles": 0, "is_primary": 0},
{"id": 296, "board_group_id": 140, "engine_id": 3, "market_id": 10, "boardid": "SPEC", "board_title": "Поставка - безадресные", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 256, "board_group_id": 88, "engine_id": 3, "market_id": 34, "boardid": "FUTS", "board_title": "Фьючерсы системные - безадрес.", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 257, "board_group_id": 89, "engine_id": 3, "market_id": 34, "boardid": "FUTN", "board_title": "Фьючерсы внесистемные- адрес.", "is_traded": 0, "has_candles": 1, "is_primary": 0},
{"id": 321, "board_group_id": 165, "engine_id": 3, "market_id": 41, "boardid": "FIXI", "board_title": "Валютный фиксинг", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 411, "board_group_id": 261, "engine_id": 3, "market_id": 45, "boardid": "OTCT", "board_title": "Рынок OTC", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 413, "board_group_id": 263, "engine_id": 3, "market_id": 45, "boardid": "OTCF", "board_title": "Рынок OTC крупные сделки", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 22, "board_group_id": 15, "engine_id": 4, "market_id": 12, "boardid": "FOB", "board_title": "Фьючерсы и Опционы", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 101, "board_group_id": 45, "engine_id": 4, "market_id": 22, "boardid": "RFUD", "board_title": "Фьючерсы", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 103, "board_group_id": 35, "engine_id": 4, "market_id": 24, "boardid": "ROPD", "board_title": "Опционы", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 294, "board_group_id": 138, "engine_id": 4, "market_id": 37, "boardid": "FIQS", "board_title": "Фьючерсы IQS", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 295, "board_group_id": 139, "engine_id": 4, "market_id": 38, "boardid": "OIQS", "board_title": "Опционы IQS", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 80, "board_group_id": 20, "engine_id": 5, "market_id": 18, "boardid": "FOCM", "board_title": "Фьючерсы на товарные активы", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 94, "board_group_id": 24, "engine_id": 6, "market_id": 20, "boardid": "GSEL", "board_title": "Интервенции по продаже зерна", "is_traded": 1, "has_candles": 0, "is_primary": 1},
{"id": 297, "board_group_id": 141, "engine_id": 7, "market_id": 39, "boardid": "OBBO", "board_title": "ОТС-система: облигации", "is_traded": 0, "has_candles": 1, "is_primary": 1},
{"id": 427, "board_group_id": 271, "engine_id": 9, "market_id": 51, "boardid": "SUGR", "board_title": "Агро: Сахар", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 1036, "board_group_id": 1032, "engine_id": 9, "market_id": 1031, "boardid": "AIGR", "board_title": "Агро: Аукционы НТБ", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 1090, "board_group_id": 1085, "engine_id": 9, "market_id": 1084, "boardid": "ABGR", "board_title": "Агро: Закупочные аукционы НТБ", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 1022, "board_group_id": 1021, "engine_id": 1012, "market_id": 1013, "boardid": "OCTR", "board_title": "ОТС: Облигации Т+ - безадресные", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 1016, "board_group_id": 1015, "engine_id": 1012, "market_id": 1013, "boardid": "OCTU", "board_title": "ОТС: Облигации Т+ (USD) - безадресные", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1018, "board_group_id": 1017, "engine_id": 1012, "market_id": 1014, "boardid": "OCBR", "board_title": "OTC: Облигации с ЦК - двусторонние", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 1205, "board_group_id": 1204, "engine_id": 1012, "market_id": 1014, "boardid": "OCBY", "board_title": "OTC: Облигации с ЦК (CNY) - двусторонние", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1020, "board_group_id": 1019, "engine_id": 1012, "market_id": 1014, "boardid": "OCBU", "board_title": "OTC: Облигации с ЦК (USD) - двусторонние", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1264, "board_group_id": 1263, "engine_id": 1012, "market_id": 1014, "boardid": "OCAR", "board_title": "OTC: Облигации с ЦК адрес. - двусторонние", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1266, "board_group_id": 1265, "engine_id": 1012, "market_id": 1014, "boardid": "OCAY", "board_title": "OTC: Облигации с ЦК адрес. (CNY) - двусторонние", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1268, "board_group_id": 1267, "engine_id": 1012, "market_id": 1014, "boardid": "OCAU", "board_title": "OTC: Облигации с ЦК адрес. (USD) - двусторонние", "is_traded": 1, "has_candles": 1, "is_primary": 0},
{"id": 1259, "board_group_id": 1258, "engine_id": 1012, "market_id": 1257, "boardid": "MTQR", "board_title": "ОТС: Акции Т+ - безадресные", "is_traded": 1, "has_candles": 1, "is_primary": 1},
{"id": 1261, "board_group_id": 1260, "engine_id": 1012, "market_id": 1262, "boardid": "MPTR", "board_title": "ОТС: Акции РПС с ЦК - адресные", "is_traded": 1, "has_candles": 1, "is_primary": 0}
]')